config/routes.rb
Rails.application.routes.draw do

  get 'user_lessons/create'

  get 'user_lessons/destroy'

  get 'filters/show'

  scope "(:locale)" do
    root 'static_pages#home'

    resources :lesson_details, only: [:show]
    resources :user_lessons, only: [:create, :destroy]

    resources :topics, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :lessons, only: [:index, :show, :new, :create]
    end

    devise_for :users

    devise_scope :users do
      resources :profiles, except: [:index]
    end
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    # @available_lessons = Lesson.all.order(:lesson_date)
    @available_lessons = Lesson.filter(params.slice(:country, :contains)).where('lesson_date >= ?', Date.today).order(:lesson_date)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_available_lesson.html.erb
<%= link_to lesson_detail_path(available_lesson), remote: true do %>

  <div class="col-xs-6 col-sm-6 col-md-3">
    <div class="thumbnail card home-thumb">
      <%= image_tag available_lesson.topic.picture.url %>
      <div class="title">
        <h3 class="hidden-xs"><%= available_lesson.topic.title %></h3>
        <h5 class="visible-xs"><%= available_lesson.topic.title %></h5>
      </div>
      <div class="caption">
        <%= available_lesson.lesson_date.strftime("%A, %d %B") %> - <%= available_lesson.lesson_date.strftime("%H:%M") %>
      </div>
    </div>
  </div>

<% end %>

app/views/static_pages/_dialog.html.erb
<div class="modal fade"
     id="dialog" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel"
     aria-hidden="true"
     data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close"
                data-dismiss="modal"
                aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/static_pages/home.html.erb
<div class="row">
  <div class="col-sm-12 hidden-md hidden-lg center">
    <%= link_to("Apply filters", filters_show_path, remote: true) %>
    <br><br>
  </div>
</div>
<div class="row">
  <%= render partial: "available_lesson", collection: @available_lessons %>
</div>