config/routes.rb
Rails.application.routes.draw do

  get 'user_lessons/create'

  get 'user_lessons/destroy'

  get 'filters/show'

  scope "(:locale)" do
    root 'static_pages#home'

    resources :lesson_details, only: [:show]
    resources :user_lessons, only: [:create, :destroy]

    resources :topics, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :lessons, only: [:index, :show, :new, :create]
    end

    devise_for :users

    devise_scope :users do
      resources :profiles, except: [:index]
    end
  end


end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :lessons, dependent: :destroy, inverse_of: :topic
  has_many :subscribed_users, through: :lessons

  validates :title,  presence: true, length: { maximum: 18 }
  validates :excerpt,  presence: true, length: { maximum: 140 }
  validates :description,  presence: true
  validates :picture,  presence: true

  validate  :picture_size

  mount_uploader :picture, PictureUploader

  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 1.megabytes
        errors.add(:picture, "should be less than 1MB")
      end
    end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  def index
    if current_user.topics.count != 0
      @topics = current_user.topics
    else
      flash[:danger] = "You didn't create any Topic yet! Create one now!"
      redirect_to new_topic_path
    end
  end

  def show
    @topic = Topic.find(params[:id])
    @lessons = @topic.lessons
  end

  def new
    @topic = current_user.topics.build
  end

  def create
    @topic = current_user.topics.build(topic_params)
    if @topic.save
      flash[:success] = "Topic created"
      redirect_to topics_path
    else
      flash[:danger] = "Houston, we got a problem!"
      render 'new'
    end
  end

  def edit
  end

  def update
    # @topic is already defined in correct_user which is called before_action
    if @topic.update_attributes(topic_params)
      flash[:success] = "Topic updated"
      redirect_to @topic
    else
      render 'edit'
    end
  end

  def destroy
    @topic.destroy
    flash[:success] = "Topic deleted"
    redirect_to topics_path
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :excerpt, :description, :picture, :category)
  end

  def correct_user
    @topic = current_user.topics.find_by(id: params[:id])
    if @topic.nil?
      flash[:danger] = "You can't access this topic!"
      redirect_to root_url
    end
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_topic.html.erb
<div class="col-xs-12 col-sm-6 col-md-4">
  <%= link_to(topic) do %>
  <div class="thumbnail element">
    <% if topic.picture? %>
        <%= image_tag topic.picture.url %>
    <% end %>
    <div class="caption">
      <h3><%= topic.title %></h3>
    </div>
    <div class="caption card-meta">
      <span><i class="glyphicon glyphicon-user"></i> <%= topic.subscribed_users.count %></span>
      <span><i class="glyphicon glyphicon-bookmark"></i> <%= topic.lessons.count %></span>
      <span class="right"><i class="glyphicon glyphicon-tag"></i> <%= topic.category %></span>
    </div>
  </div>
  <% end %>
</div>

app/views/topics/create.html.erb
<h1>Topics#create</h1>
<p>Find me in app/views/topics/create.html.erb</p>

app/views/topics/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <h1>Edit Topic</h1>

    <%= form_for(@topic) do |f| %>

      <%= f.text_field :title, class: 'form' %>

      <div id="charNum">140</div>
      <%= f.text_area :excerpt, id: 'excerpt', class: 'form', onkeyup: 'countChar(this)', required: 'required', placeholder: 'Brief summary (max 140 char)' %>

      <%= f.text_area :description, id: 'description', class: 'form', required: 'required', placeholder: 'Long description' %>

      <%= f.submit "Save changes", class: "form-btn" %>
    <% end %>
    <hr>


    <%= button_to "Back", @topic, method: :get, class: 'form-btn blue' %>

    <br>

    <%= button_to "Delete Lesson", @topic, method: :delete, class: 'form-btn red', data: { confirm: "You sure?" }  %>

  </div>
</div>

app/views/topics/index.html.erb
<div class="row">
  <%= render @topics %>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12">
    <p><i class="glyphicon glyphicon-fire"></i> = number of people who joined any lesson of the topic</p>
    <p><i class="glyphicon glyphicon-bookmark"></i> = number of lessons of the topic</p>
  </div>
</div>

app/views/topics/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <h1>Create Topic</h1>

    <%= form_for @topic do |f| %>

        <%= render 'shared/error_messages', object: f.object %>

        <%= f.text_field :title, id: 'title', class: 'form', required: 'required', placeholder: 'Topic title' %>

        <%= f.select :category, [['Sport', 'Sport'], ['Dance and Music', 'Dance and Music']], id: 'category', required: 'required' %>

        <%= f.label :excerpt, "140", id: :excerpt  %>
        <%= f.text_area :excerpt, id: 'excerpt', class: 'form', onkeyup: 'countChar(this, 140)', required: 'required', placeholder: 'Brief summary (max 140 char)' %>

        <%= f.label :description, "500", id: :description  %>
        <%= f.text_area :description, id: 'description', class: 'form', onkeyup: 'countChar(this, 500)', required: 'required', placeholder: 'Long description (max 500 char)' %>

        <%= f.file_field :picture, class: "form", accept: 'image/jpeg,image/gif,image/png'  %>

        <%= f.submit "Add", class: "form-btn" %>
    <% end %>

    <hr>
    <%= button_to "Back", @topic, method: :get, class: 'form-btn blue' %>

  </div>
</div>

app/views/topics/show.html.erb
<div class="row bottom-padding">
  <div class="col-xs-12 col-sm-8 col-md-6">

    <h3><strong>Topic name:</strong> <%= @topic.title %></h3>

    <div class="topic-picture">
      <% if @topic.picture? %>
          <%= image_tag @topic.picture.url %>
      <% end %>
    </div>

    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingOne">
          <h4 class="panel-title">
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              Brief Description
            </a>
          </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
          <div class="panel-body">
            <p><%= @topic.excerpt %></p>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingTwo">
          <h4 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              Long description
            </a>
          </h4>
        </div>
        <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
          <div class="panel-body">
            <%= @topic.description %>
          </div>
        </div>
      </div>
    </div>

    <%= button_to "Edit Details", edit_topic_path, method: :get, class: 'form-btn' %>

  </div>

  <div class="col-xs-12 col-sm-4 col-md-6 align-left">

    <h3><strong>List of lessons:</strong></h3>

    <% if @topic.lessons.any? %>
      <div class="row">
        <%= render @lessons %>
      </div> <!-- row -->
    <% else %>
      <p>You do not have any lesson scheduled yet! Add your first lesson!</p>
    <% end %>

    <%= button_to "New occurrency", new_topic_lesson_path(@topic), method: :get, class: 'form-btn' %>

  </div>

</div> <!-- row -->