config/routes.rb
Rails.application.routes.draw do

  get 'user_lessons/create'

  get 'user_lessons/destroy'

  get 'filters/show'

  scope "(:locale)" do
    root 'static_pages#home'

    resources :lesson_details, only: [:show]
    resources :user_lessons, only: [:create, :destroy]

    resources :topics, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :lessons, only: [:index, :show, :new, :create]
    end

    devise_for :users

    devise_scope :users do
      resources :profiles, except: [:index]
    end
  end


end

app/views/layouts/_flashmessages.html.erb
<div id="notice">
  <% flash.each do |key, value| %>
      <% alert_class = case key
                         when "notice" then "success"
                         when "alert" then "danger"
                         else key
                       end %>
      <%= content_tag :div, class: "alert alert-#{alert_class}" do %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= value %>
      <% end %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    An awesome application made by Davide & Martin
  </small>
</footer>

app/views/layouts/_header.html.erb
<nav id="navbar" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button href="#menu-toggle" class="slidebar-toggle" id="menu-toggle">
      <span class="sr-only">Toggle sidebar</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-123">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <span><%= link_to('TryFree', root_path, class: 'navbar-brand') %></span>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-123">
    <div class="container-fluid">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle dropdown-toggle-hide" data-toggle="dropdown"> <%= current_user.email %> <b class="caret"></b></a>
              <ul class="dropdown-menu dropdown-menu-hide">
                <li><%= link_to('<i class="glyphicon glyphicon-edit"></i> Edit Profile'.html_safe, edit_user_registration_path, class: 'dropmenu-item-btn') %></li>
                <li><%= link_to('<i class="glyphicon glyphicon-comment"></i> Notifications'.html_safe, '#', class: 'dropmenu-item-btn') %></li>
                <li class="divider"></li>
                <li><%= link_to('<i class="glyphicon glyphicon-log-out"></i> Log Out  '.html_safe, destroy_user_session_path, method: 'delete', class: 'dropmenu-item-btn') %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to '<i class="glyphicon glyphicon-log-in"></i> Log In'.html_safe, new_user_session_path %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= locale %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% alternate_locales do |l| %>
                <li class="dropmenu-item-btn"><%= link_to(l, "/"+l.to_s ) %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<!-- Sidebar -->
<div id="slidebar-white" class="slidebar-nav">
  <nav id="navbar-white" class="navbar navbar-default" role="navigation">
    <ul class="nav navbar-nav">

      <li><%= link_to('<i class="glyphicon glyphicon-tags"></i> Filters'.html_safe, filters_show_path, remote: true, id: 'slide-btn') %></li>
      <li><%= link_to('<i class="glyphicon glyphicon-th-large"></i> All Lessons'.html_safe, root_path, id: 'slide-btn') %></li>

      <li class="dropdown bottom-padding">
        <a href="#" class="dropdown-toggle" id="slide-btn" data-toggle="dropdown"><i class="glyphicon glyphicon-user"></i> User menu <b class="caret"></b></a>
        <ul class="dropdown-menu">

          <% if current_user %>
             <li><%= link_to('<i class="glyphicon glyphicon-plus"></i> Create new topic'.html_safe, new_topic_path, class: 'dropmenu-item-btn') %></li>

            <% if current_user.topics.count != 0 %>
              <li><%= link_to('<i class="glyphicon glyphicon-th-large"></i> My topics'.html_safe, topics_path, class: 'dropmenu-item-btn') %></li>
            <% end %>

          <% else %>
            <li><%= link_to '<i class="glyphicon glyphicon-log-in"></i> Log In'.html_safe, new_user_session_path, class: 'dropmenu-item-btn' %></li>
          <% end %>
        </ul>
      </li>

    </ul>
  </nav><!--/.navbar -->
</div><!--/.sidebar-nav -->

<script>$("#menu-toggle").click(function(e){e.preventDefault();$("#wrapper").toggleClass("toggled");});</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tryfree</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
</head>
<body>
  <%= render 'static_pages/dialog' %>
  <%= render 'layouts/header' %>
  <div id="wrapper">
    <%= render 'layouts/sidebar' %>
    <main id="page-wrapper6">
      <div class="container-fluid">
        <%= render 'layouts/flashmessages' %>
        <%= yield %>
      </div>
    </main>
  </div><!--wrapper-->
</body>
</html>